version: '2'
services:
  auth-service:
    container_name: auth-service
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      PORT: 3001
      HOST: localhost
      NODE_ENV: development
      REDIS_PORT: 6379
      REDIS_HOST: redis
    external_links:
      - redis
    network_mode: bridge
  redis:
    container_name: redis
    image: redis:3.2.10-alpine
    network_mode: bridge
